# Shadow
shadow = false;            # Enabled client-side shadows on windows.
shadow-radius = 1;        # The blur radius for shadows. (default 12)
shadow-offset-x = -7;        # The left offset for shadows. (default -15)
shadow-offset-y = -7;        # The top offset for shadows. (default -15)
shadow-opacity = 0.7;        # The translucency for shadows. (default .75)
blur-background = true;
blur-background-frame = false;
blur-method = "dual_kawase";
blur-strength = 10;
blur-background-fixed = true;

backend = "glx";

shadow-exclude = [ "n:e:Notification"];
shadow-ignore-shaped = true;

# Opacity
opacity-rule = [
    "100:_NET_WM_STATE@[0]:32a *= '_NET_WM_STATE_FULLSCREEN'",
    "100:_NET_WM_STATE@[1]:32a *= '_NET_WM_STATE_FULLSCREEN'",
    "100:_NET_WM_STATE@[2]:32a *= '_NET_WM_STATE_FULLSCREEN'",
    "100:_NET_WM_STATE@[3]:32a *= '_NET_WM_STATE_FULLSCREEN'",
    "100:_NET_WM_STATE@[4]:32a *= '_NET_WM_STATE_FULLSCREEN'",
    "100:class_g = 'zoom'",
    "100:class_g = 'polybar'",
    "95:focused",
    "80:!focused",
    "70:class_g = 'rofi'",
];

# Fading
fading = true;            # Fade windows during opacity changes.
fade-in-step = 0.03;        # Opacity change between steps while fading in. (default 0.028).
fade-out-step = 0.03;        # Opacity change between steps while fading out. (default 0.03).

# Window type settings
wintypes:
{
  tooltip = { fade = true; shadow = false; opacity = 0.75; };
  dock = { shadow = false };
  dnd = { shadow = false };
};
